# Permalinks
permalink:           pretty

# Setup
title:               Mariana Franco
tagline:             Software Engineer
url:                 https://marianafranco.github.io
paginate:            5
baseurl:             ""

# Assets
#
# We specify the directory for Jekyll so we can use @imports.
# sass:
#   sass_dir:         _assets
#   style:            :compressed

# About/contact
author:
  name:              Mariana Ramos Franco
  url:               http://marianafranco.github.io

# Custom vars
version:             2.0.0
github:
  repo:              https://github.com/marianafranco/marianafranco.github.io

# This is the list of pages to include in the header of the website.
pages_list:
  About: '/about/'
  Projects: '/projects/'

assets:
  compress:
    css: true
  js_compressor:  uglifier
  css_compressor: scss
  features:
    liquid: true

# Gems
gems:
  - jekyll-paginate
  - jekyll-gist
  - jekyll-sitemap
  - jekyll-assets
