name: Mariana Franco
subname: Software Engineer

description: My personal blog
url: http://marianafranco.github.io

markdown: redcarpet
#highlighter: true
excerpt_separator: <!--more-->

# Permalinks
permalink: pretty

# This is the list of pages to incldue in the header of the website.
pages_list:
  About: '/about/'
  Projects: '/projects/'
